tabs:
  - direction: Vertical
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
            focus: true
            split_size:
              Percent: 90
          - direction: Vertical
            split_size:
              Percent: 90
      - direction: Horizontal
